config/routes.rb
Rails.application.routes.draw do
  root "scans#index"

  get "/js_qr", to: "scans#js_qr", as: :js_qr
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/scans_controller.rb
class ScansController < ApplicationController
  def index; end

  def js_qr; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoScanQr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scans/_js_qr.js.erb
var video = document.createElement("video");
var canvasElement = document.getElementById("canvas");
var canvas = canvasElement.getContext("2d");

navigator.mediaDevices.getUserMedia({
  video: {
    facingMode: "environment"
  }
}).then(function(stream) {
    video.srcObject = stream;
    video.setAttribute("playsinline", true);
    video.play();
    requestAnimationFrame(tick);
  }
);

function tick() {
  if (video.readyState === video.HAVE_ENOUGH_DATA) {
    canvasElement.hidden = false;
    canvas.drawImage(video, 0, 0, canvasElement.width, canvasElement.height);

    var imageData = canvas.getImageData(0, 0, canvasElement.width, canvasElement.height);
    var code = jsQR(imageData.data, imageData.width, imageData.height, {
      inversionAttempts: "dontInvert"
    });

    if (code) {
      drawLine(code.location.topLeftCorner, code.location.topRightCorner, "#FF3B58");
      drawLine(code.location.topRightCorner, code.location.bottomRightCorner, "#FF3B58");
      drawLine(code.location.bottomRightCorner, code.location.bottomLeftCorner, "#FF3B58");
      drawLine(code.location.bottomLeftCorner, code.location.topLeftCorner, "#FF3B58");

      alert(code.data)
    }
  }
  requestAnimationFrame(tick);
}

function drawLine(begin, end, color) {
  canvas.beginPath();
  canvas.moveTo(begin.x, begin.y);
  canvas.lineTo(end.x, end.y);
  canvas.lineWidth = 4;
  canvas.strokeStyle = color;
  canvas.stroke();
}

app/views/scans/index.html.erb
<div class="container">
  <h2>Demo Scan QR Code by Javascript</h2>
  <p>Updating ....</p>

  <table class="table">
    <thead>
      <tr>
        <th>No</th>
        <th>Resource</th>
        <th>Demo</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td>1</td>
        <td><%= link_to "jsQR.js", "https://github.com/cozmo/jsQR" %></td>
        <td><%= link_to "Try it", js_qr_path, class: "btn btn-primary" %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/scans/js_qr.html.erb
<div class="container">
  <h1>jsQR Demo</h1>

  <canvas id="canvas"></canvas>
</div>

<%= stylesheet_link_tag "js_qr/js_qr", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "js_qr/js_qr", "data-turbolinks-track": "reload" %>

<script type="text/javascript">
  <%= render "js_qr.js" %>
</script>